<a href="https://colab.research.google.com/github/coketaste/dl-examples/blob/main/dl_pytorch/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors: Multidimensional arrays

In [1]:
%pip install torch

# New Section

In [3]:
# From Python lists to PyTorch tensors
a = [1.0, 2.0, 1.0]
print(a[0])
print(a[2])

# Constructing our first tensors
import torch
a = torch.ones(3)
print(a)
print(a[1])
print(float(a[1]))
a[2] = 2.0
print(a)

1.0
1.0
tensor([1., 1., 1.])
tensor(1.)


In [7]:
points = torch.zeros(6)
print(points)
print(type(points))

# Change items
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
print(points)

tensor([0., 0., 0., 0., 0., 0.])
<class 'torch.Tensor'>
tensor([4., 1., 5., 3., 2., 1.])


In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])